### ISSUE TITLE
Licence incompatible

### ISSUE THREAD

**Issue by Ensam57** [paxo-phone/paxo-site#77]
Sur la page d'accueil, vous notez : Le projet Paxo adhère aux principes du logiciel libre, aussi bien au niveau du matériel que du logiciel. Cela signifie qu’il confère à chacun la liberté d'utliliser, d'étudier, d'adapter et de redistribuer les plans et le code du téléphone (**dans un cadre non-commercial**).

Si c'est dans un cadre non commercial, alors ce n'est plus du tout du logiciel et du matériel libre.

**Comment by paxo-rch** [comment]
En effet, nous préférons attendre que le projet soit plus clair dans ses prochaines étapes avant d'autoriser le cadre commercial. C'est plus pour protéger le projet au stade ou il en est. Si quelqu'un veut utiliser le projet dans un cadre commercial, libre a lui de demander.
